import {VERSION,dimensions,questions,scale,scoreAnswers,rankScores} from './data.js?v=2';
const $=id=>document.getElementById(id), key='science-explorer-v2';
let answers=Array(24).fill(null),current=0,selectedFeedback='',currentScores=[],shared=false;
function persist(){try{localStorage.setItem(key,JSON.stringify({version:VERSION,answers,current}));}catch{document.querySelector('.save-note').textContent='当前浏览器未允许保存进度';}}
try{const s=JSON.parse(localStorage.getItem(key));if(s?.version===VERSION&&Array.isArray(s.answers)&&s.answers.length===24&&s.answers.every(v=>v===null||Number.isInteger(v)&&v>=-1&&v<=4)){answers=s.answers;current=Number.isInteger(s.current)?Math.max(0,Math.min(23,s.current)):0;}}catch{}
const answered=()=>answers.filter(a=>a!==null).length;
function updateResume(){const n=answered();$('start').innerHTML=n?'继续我的探索 <span>↗</span>':'发现我的探索风格 <span>↗</span>';$('resume-note').textContent=n?`已保存 ${n} / 24 题，可继续或重新开始。`:'';$('fresh').hidden=!n;}
function screen(name){['intro','quiz','result'].forEach(id=>$(id).hidden=id!==name);$('method').hidden=name!=='intro';window.scrollTo({top:0,behavior:'instant'});}
function renderQuestion(){screen('quiz');const q=questions[current];$('counter').textContent=`${String(current+1).padStart(2,'0')} / 24`;$('progress-fill').style.width=`${answered()/24*100}%`;document.querySelector('.progress').setAttribute('aria-valuenow',answered());$('context').textContent=q.context;$('question-text').textContent=q.text;$('answers').innerHTML='<legend class="sr-only">这种情况发生的频率</legend>'+scale.map((s,i)=>`<label class="answer"><input type="radio" name="frequency" value="${i}" ${answers[current]===i?'checked':''}><span>${s}</span></label>`).join('');$('skip').setAttribute('aria-pressed',answers[current]===-1);$('previous').disabled=current===0;$('next').disabled=answers[current]===null;$('next').textContent=current===23?'看看我的风格 ↗':'下一题 →';$('question-text').focus({preventScroll:true});}
$('answers').addEventListener('change',e=>{if(e.target.name==='frequency'){answers[current]=Number(e.target.value);persist();$('next').disabled=false;$('skip').setAttribute('aria-pressed','false');$('quiz-status').textContent=`已选择：${scale[answers[current]]}`;$('progress-fill').style.width=`${answered()/24*100}%`;document.querySelector('.progress').setAttribute('aria-valuenow',answered());}});
$('skip').onclick=()=>{answers[current]=-1;persist();renderQuestion();$('quiz-status').textContent='此题已跳过，不计为低分';};
$('next').onclick=()=>{if(answers[current]===null)return;if(current<23){current++;persist();renderQuestion();}else{const missing=answers.indexOf(null);if(missing!==-1){current=missing;renderQuestion();}else showResult(scoreAnswers(answers));}};
$('previous').onclick=()=>{if(current>0){current--;persist();renderQuestion();}};
$('start').onclick=()=>{shared=false;renderQuestion();};$('back-home').onclick=()=>{screen('intro');updateResume();};
function reset(){answers=Array(24).fill(null);current=0;shared=false;history.replaceState(null,'',location.pathname);persist();renderQuestion();}
$('fresh').onclick=reset;$('restart').onclick=reset;$('edit').onclick=()=>{if(shared){screen('intro');updateResume();}else renderQuestion();};
function descriptor(score){return score===null?'有效回答不足':score>=88?'几乎总是':score>=63?'经常如此':score>=38?'有时如此':score>=13?'偶尔如此':'很少如此';}
function profile(scores){const ranked=rankScores(scores),top=ranked[0];if(!top)return {title:'还有一些未知，留给下一次',line:'这次可用的回答较少，暂时不为你归类。',art:'explorers',top:null,ranked};const close=ranked.filter(d=>top.score-d.score<=12.5);const low=top.score<50;const balanced=close.length>=3;return {title:low?'探索方式仍在展开':balanced?'多面探索者':top.title,line:low?'这些情境目前较少出现在你的生活中，暂时不必用一个类型概括自己。':balanced?'你会根据问题切换不同方式，当前没有一个明显独占的方向。':top.line,art:balanced||low?'explorers':top.id,top,ranked,balanced,low};}
function showResult(scores){currentScores=scores;const p=profile(scores);screen('result');$('result-title').textContent=p.title;$('result-english').textContent=p.balanced?'Multifaceted Explorer':p.low||!p.top?'An Exploration in Progress':p.top.english;$('result-line').textContent=p.line;$('result-art').src=`assets/${p.art}.svg`;$('result-art').alt=p.art==='explorers'?'六位科学家组成的探索群像':`${p.top.scientist}原创几何插画`;$('scientist-name').textContent=p.art==='explorers'?'不同方式，可以在你身上相遇':`科学史中的呼应 · ${p.top.scientist}`;$('history-note').textContent=p.art==='explorers'?'人物是科学史的灵感参照，不是人格测量。':p.top.history;
const ties=p.top?p.ranked.filter(d=>d.score===p.top.score):[];$('secondary-style').hidden=!p.top;$('secondary-style').textContent=ties.length>1?`并列倾向：${ties.map(d=>d.name).join(' · ')}`:p.ranked[1]?`同时伴随：${p.ranked[1].name} · ${p.ranked[1].title}`:`当前可描述的方向：${p.top?.name||''}`;
const incomplete=scores.filter(d=>d.score===null).length;$('result-caveat').textContent=(shared?'这是对方分享的探索轮廓。':'这是你此次回答的摘要，不是能力分数。')+(incomplete?` ${incomplete} 个方向因有效回答不足，未参与比较。`:'');$('edit').textContent=shared?'我也来探索 ↗':'← 修改答案';
const insights=p.top&&!p.low&&!p.balanced?[['常见的优势',p.top.strength],['值得留意的另一面',p.top.blind],['下一次可以试试',p.top.action]]:[['允许多种方式共存','你不需要在观察、想象和实践之间选择唯一身份。具体的问题常常需要几种方式配合。'],['先看看情境','如果某些题很难代入，可能是你暂时没有这样的经历，不必把它理解成能力不足。'],['从一件小事开始','找一件最近让你好奇的事，先记录一个细节，再提出一个解释，最后做一次小尝试。']];$('insights').innerHTML=insights.map(([title,text],i)=>`<article class="insight"><div class="number">0${i+1}</div><h3>${title}</h3><p>${text}</p></article>`).join('');if(p.top&&!p.low&&!p.balanced){const item=document.createElement('p');item.className='small';item.style.marginTop='18px';item.textContent='合作小建议：'+p.top.partner;$('insights').lastElementChild.appendChild(item);}
$('bars').innerHTML=scores.map(d=>`<div class="bar-row"><div class="bar-label"><strong>${d.name}</strong><span>${descriptor(d.score)}${d.count<4?` · ${d.count}/4 题`:''}</span></div><div class="bar-track" role="img" aria-label="${d.name}：${descriptor(d.score)}"><span style="width:${d.score??0}%;background:${d.color}"></span></div></div>`).join('');$('share-status').textContent='';$('result-title').focus({preventScroll:true});}
$('type-gallery').innerHTML=dimensions.map(d=>`<article class="type-card"><img src="assets/${d.id}.svg" width="400" height="400" loading="lazy" alt="${d.scientist}原创几何插画"><strong>${d.title}</strong><span class="type-english" lang="en">${d.english}</span><span>${d.name}</span></article>`).join('');
function resultURL(){const s=currentScores.map(d=>`${d.score===null?'x':d.score}.${d.count}`).join(',');return `${location.origin}${location.pathname}#profile=${s}`;}
async function copyText(text,status){try{await navigator.clipboard.writeText(text);$(status).textContent='已复制。';}catch{$(status).textContent='浏览器未允许自动复制，请选中下面的文字复制。';const box=document.createElement('textarea');box.value=text;box.rows=4;box.style.width='100%';$(status).appendChild(box);box.select();}}
$('copy').onclick=()=>copyText(`${profile(currentScores).title} · 我的科学探索风格\n${resultURL()}`,'share-status');
function wrapText(ctx,text,x,y,width,lineHeight){let line='';for(const c of text){if(ctx.measureText(line+c).width>width){ctx.fillText(line,x,y);line=c;y+=lineHeight;}else line+=c;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
$('save').onclick=async()=>{const button=$('save');button.disabled=true;try{const p=profile(currentScores);const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1320;const ctx=canvas.getContext('2d');ctx.fillStyle='#f7f6f2';ctx.fillRect(0,0,1000,1320);ctx.fillStyle='#326f5d';ctx.font='18px sans-serif';ctx.fillText('科学探索风格',70,75);ctx.fillStyle='#253f3b';ctx.font='bold 49px sans-serif';wrapText(ctx,p.title,70,145,860,65);ctx.fillStyle='#687974';ctx.font='22px sans-serif';ctx.fillText(p.balanced?'Multifaceted Explorer':p.low||!p.top?'An Exploration in Progress':p.top.english,70,192);const img=new Image();img.src=`assets/${p.art}.svg`;await img.decode();ctx.drawImage(img,300,220,400,400);ctx.fillStyle='#687974';ctx.font='24px sans-serif';wrapText(ctx,p.line,90,675,820,40);currentScores.forEach((d,i)=>{const y=800+i*61;ctx.fillStyle='#253f3b';ctx.font='21px sans-serif';ctx.fillText(d.name,90,y);ctx.fillStyle='#e0e6dd';ctx.fillRect(265,y-17,430,12);ctx.fillStyle=d.color;ctx.fillRect(265,y-17,430*(d.score??0)/100,12);ctx.fillStyle='#687974';ctx.font='18px sans-serif';ctx.fillText(descriptor(d.score),730,y);});ctx.fillStyle='#687974';ctx.font='19px sans-serif';ctx.fillText('探索偏好，不是能力评判。',90,1220);ctx.font='16px sans-serif';ctx.fillText('hongjiangyang.github.io/science-temperament-quiz/',90,1260);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-exploration-style.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('share-status').textContent='结果卡已生成。若手机浏览器打开了图片，可长按保存。';}catch{$('share-status').textContent='暂时无法生成图片，请先使用复制结果链接。';}finally{button.disabled=false;}};
$('feedback-buttons').onclick=e=>{const value=e.target.dataset.feedback;if(!value)return;selectedFeedback=value;document.querySelectorAll('[data-feedback]').forEach(b=>b.setAttribute('aria-pressed',b===e.target));};$('copy-feedback').onclick=()=>copyText(`科学探索风格反馈 v${VERSION}\n结果：${profile(currentScores).title}\n感受：${selectedFeedback||'未选择'}\n补充：${$('feedback-text').value.trim()||'无'}`,'feedback-status');
$('clear-data').onclick=()=>{try{localStorage.removeItem(key);}catch{}answers=Array(24).fill(null);current=0;currentScores=[];shared=false;selectedFeedback='';$('feedback-text').value='';document.querySelectorAll('[data-feedback]').forEach(b=>b.setAttribute('aria-pressed','false'));history.replaceState(null,'',location.pathname);screen('intro');updateResume();$('data-status').textContent='此浏览器中的测试记录已清除。';};
updateResume();
function readSharedProfile(){if(location.hash.startsWith('#profile=')){const parts=location.hash.slice(9).split(',');if(parts.length===6){const parsed=parts.map((s,i)=>{const [value,n]=s.split('.'),count=Number(n),score=value==='x'?null:Number(value);return {...dimensions[i],count,score};});if(parsed.every(d=>Number.isInteger(d.count)&&d.count>=0&&d.count<=4&&(d.score===null?d.count<3:Number.isInteger(d.score)&&d.score>=0&&d.score<=100&&d.count>=3))){shared=true;showResult(parsed);}}}

}
window.addEventListener('hashchange',readSharedProfile);
readSharedProfile();
