import {axes,questions,families,types,score,classify,clarity} from './data.js?v=4.0';
const $=s=>document.querySelector(s), letters=[['S','C'],['O','T'],['E','R'],['W','D']],words=[['Solo','Collaborative'],['Observe','Try'],['Examples','Relations'],['Wide','Deep']];
const code=t=>t.bits.map((b,i)=>letters[i][b]).join('');
let answers=Array(48).fill(null),page=0,ties={},scores=[],currentType=null;
const sections=['home','guide','quiz','tie','result'];
function show(id){sections.forEach(s=>$('#'+s).hidden=s!==id);window.scrollTo(0,0);}
function modal(content){$('#modal-content').innerHTML=content;$('#modal').showModal();}
$('#close-modal').onclick=()=>$('#modal').close();
$('#about').onclick=()=>modal(`<h2>关于探索性格测试</h2><p>用 48 个日常情境，描绘四组探索偏好。16 个角色只是便于理解和交流的描述，没有优劣，也不代表固定身份。</p><p>内容参考跨学科人物探索过程研究，四条轴和题目为原创设计，尚未完成独立样本的信效度验证。不是对人物的性格测量，也不能证明这套分类一定成立。</p><p>不要求填写身份信息；不上传回答，不使用分析或追踪工具。答题仅在当前页面内存中计算，刷新或关闭后清除。本测试不收集反馈。托管平台可能保留常规访问日志。</p>`);
$('#gallery').innerHTML=families.map((f,i)=>`<div class="family-group" style="--accent:${f.color};--bg:${f.bg}"><h3 style="color:${f.color}">${f.name}</h3><p>${f.line}</p><div class="type-grid">${types.filter(t=>t.family===i).map(t=>`<button class="type-tile" data-type="${t.id}"><img src="assets/type-${t.id}.svg" width="400" height="370" loading="lazy" alt=""><b>${t.name}</b><small>${code(t)}</small></button>`).join('')}</div></div>`).join('');
$('#gallery').onclick=e=>{const b=e.target.closest('[data-type]');if(!b)return;const t=types[+b.dataset.type];modal(`<img src="assets/type-${t.id}.svg" alt="${t.name}"><h2>${t.name} · ${code(t)}</h2><p>${t.english} / ${families[t.family].name}</p>${axes.map((a,i)=>`<p><b>${t.bits[i]?a.right:a.left}</b>：${a.detail[t.bits[i]]}</p>`).join('')}<p>这些是偏好组合的描述，不是能力或职业适配评价。</p>`);};
$('#start').onclick=()=>show('guide');$('#begin').onclick=()=>{show('quiz');render();};
const sizes=[44,36,28,20,28,36,44];
function render(){const subset=questions.slice(page*6,page*6+6);$('#page-label').textContent=`第 ${page+1} / 8 页`;$('#question-list').innerHTML=subset.map(q=>`<fieldset id="q-${q.id}"><legend><span>${String(q.id+1).padStart(2,'0')}</span>${q.text}</legend><div class="endpoints"><span>${q.left}</span><span>${q.right}</span></div><div class="scale">${sizes.map((s,i)=>{const v=i-3,label=v===0?'两边差不多':`${v<0?'左':'右'}侧${['','轻微','较为','明显'][Math.abs(v)]}：${v<0?q.left:q.right}`;return `<label class="choice" title="${label}" style="--size:${s}px;--circle:${v<0?'#36857d':v>0?'#8160ae':'#9b9ca8'}"><input type="radio" name="q${q.id}" value="${v}" aria-label="${label}" ${answers[q.id]===v?'checked':''}><span class="orb"></span></label>`;}).join('')}</div><div class="scale-labels"><span>明显偏左</span><span>两边差不多</span><span>明显偏右</span></div></fieldset>`).join('');$('#previous').disabled=page===0;$('#next').textContent=page===7?'查看探索性格 →':'下一页 →';$('#validation').textContent='';updateProgress();}
function updateProgress(){const n=answers.filter(Number.isInteger).length;$('#answered').textContent=`已回答 ${n} / 48`;$('progress').value=n;}
$('#question-list').onchange=e=>{const i=+e.target.name.slice(1);answers[i]=+e.target.value;$('#q-'+i).classList.remove('missing');updateProgress();};
$('#question-list').onsubmit=e=>e.preventDefault();
$('#next').onclick=()=>{const missing=questions.slice(page*6,page*6+6).filter(q=>!Number.isInteger(answers[q.id]));if(missing.length){$('#validation').textContent=`还有 ${missing.length} 道题未选择。`;missing.forEach(q=>$('#q-'+q.id).classList.add('missing'));$('#q-'+missing[0].id).scrollIntoView({block:'center'});$('#q-'+missing[0].id+' input').focus({preventScroll:true});return;}if(page<7){page++;render();window.scrollTo(0,0);$('#quiz-title').focus({preventScroll:true});}else finish();};
$('#previous').onclick=()=>{if(page>0){page--;render();window.scrollTo(0,0);}};
function finish(){scores=score(answers);ties={};if(scores.some(s=>s===0)){show('tie');$('#tie-list').innerHTML=scores.map((s,i)=>s===0?`<section><h3>${axes[i].name}</h3>${[0,1].map(b=>`<label><input type="radio" name="tie${i}" value="${b}"> ${b?axes[i].right:axes[i].left}：${axes[i].detail[b]}</label>`).join('')}</section>`:'').join('');$('#tie-finish').disabled=true;}else result();}
$('#tie-list').onchange=e=>{ties[+e.target.name.slice(3)]=+e.target.value;$('#tie-finish').disabled=!classify(scores,ties);};$('#tie-finish').onclick=()=>result();$('#tie-back').onclick=()=>{show('quiz');render();};
function result(){currentType=classify(scores,ties);if(!currentType)return;const t=currentType,f=families[t.family],c=clarity(scores);show('result');$('#result-card').style.setProperty('--accent',f.color);$('#result-card').style.setProperty('--bg',f.bg);$('#family-label').textContent=f.name;$('#result-title').textContent=t.name;$('#result-english').textContent=t.english;$('#result-code').textContent=code(t);$('#result-art').src=`assets/type-${t.id}.svg`;$('#result-art').alt=t.name+'的原创角色插画';$('#result-line').textContent=f.line;$('#bars').innerHTML=axes.map((a,i)=>`<div class="bar-row"><div class="bar-label"><${scores[i]<0?'strong':'span'}>${a.left}</${scores[i]<0?'strong':'span'}><${scores[i]>0?'strong':'span'}>${a.right}</${scores[i]>0?'strong':'span'}></div><div class="track" role="img" aria-label="${a.name}：${scores[i]===0?'两端持平':(scores[i]<0?a.left:a.right)+'，偏离中点 '+Math.round(Math.abs(scores[i])*100)+'%'}" style="--position:${50+scores[i]*48}%"><b></b></div></div>`).join('');$('#clarity-value').textContent=c+'%';$('#clarity-note').textContent=scores.some(s=>s===0)?'部分偏好持平；代表角色参考了你的补充选择。':c<34?'两端都留有空间，相邻类型也可能与你相像。':'反映本次回答的偏向程度，不是能力或排名。';$('#insights').innerHTML=axes.map((a,i)=>`<div><h3>${letters[i][t.bits[i]]} · ${t.bits[i]?a.right:a.left}${scores[i]===0?'（两端持平）':''}</h3><p>${a.detail[t.bits[i]]}</p><p>换个角度试试：${a.tip[t.bits[i]]}</p></div>`).join('');$('#code-explanation').innerHTML=axes.map((a,i)=>`<p><b>${letters[i].join(' / ')}</b>：${a.left}（${words[i][0]}） / ${a.right}（${words[i][1]}）</p>`).join('');}
$('#restart').onclick=()=>{answers=Array(48).fill(null);ties={};currentType=null;page=0;$('#action-status').textContent='';show('guide');};$('#browse').onclick=()=>{show('home');$('#gallery').scrollIntoView();};
$('#share').onclick=async()=>{const url=location.origin+location.pathname;try{if(navigator.share)await navigator.share({title:'探索性格测试',text:'你是哪一种探索者？',url});else{await navigator.clipboard.writeText(url);$('#action-status').textContent='测试链接已复制，不包含你的回答或结果。';}}catch(e){if(e.name!=='AbortError')$('#action-status').textContent='可以复制浏览器地址，分享这个测试。';}};
$('#save').onclick=async()=>{const t=currentType;if(!t)return;const button=$('#save');button.disabled=true;try{await document.fonts.ready;const c=document.createElement('canvas');c.width=1000;c.height=1200;const g=c.getContext('2d'),f=families[t.family];g.fillStyle='#fafbf7';g.fillRect(0,0,1000,1200);g.fillStyle=f.bg;g.beginPath();g.arc(845,230,320,0,Math.PI*2);g.fill();const text=(s,x,y,size,color='#283c40',weight=400)=>{g.fillStyle=color;g.font=`${weight} ${size}px "Microsoft YaHei",sans-serif`;g.fillText(s,x,y);};text('我的探索性格',65,77,24,f.color,600);text(f.name,65,154,23,f.color);text(t.name,65,220,53,'#283c40',700);text(t.english,65,267,24,'#7c8780');text(code(t),65,330,49,f.color,750);const im=new Image();im.src=`assets/type-${t.id}.svg`;await im.decode();g.drawImage(im,535,78,430,398);text(f.line,65,460,27);axes.forEach((a,i)=>{const y=535+i*112;text(a.left,65,y,26,scores[i]<0?f.color:'#768177');g.textAlign='right';text(a.right,935,y,26,scores[i]>0?f.color:'#768177');g.textAlign='left';g.fillStyle='#dee5da';g.fillRect(70,y+24,860,10);g.fillStyle='#a2ae9d';g.fillRect(499,y+18,2,22);g.fillStyle=f.color;g.beginPath();g.arc(500+scores[i]*420,y+29,12,0,Math.PI*2);g.fill();});text('倾向清晰度',65,1030,25);text(clarity(scores)+'%',818,1030,32,f.color,700);text(scores.some(s=>s===0)?'部分偏好持平；代表角色参考了补充选择。':'偏向程度不是能力、排名或统计置信度。',65,1077,22,'#7d887c');text('偏好不是能力，类型不是边界。',284,1155,24,'#8b9587');const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('png');const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`探索性格-${code(t)}-${t.name}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);$('#action-status').textContent='结果卡已生成。';}catch{$('#action-status').textContent='保存未成功，可以直接截取上方结果卡。';}finally{button.disabled=false;}};
